spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456

from: git-dev-6.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/